version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5

  coordinator:
    build: ./coordinator
    ports:
      - "8000:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  service1:
    build: ./service1
    ports:
      - "8001:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SERVICE_NAME=service1
    depends_on:
      rabbitmq:
        condition: service_healthy

  service2:
    build: ./service2
    ports:
      - "8002:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SERVICE_NAME=service2
    depends_on:
      rabbitmq:
        condition: service_healthy
